/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as CharitiesRouteImport } from './routes/charities'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CharitiesIdRouteImport } from './routes/charities.$id'
import { Route as AdminWinnersRouteImport } from './routes/admin.winners'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const CharitiesRoute = CharitiesRouteImport.update({
  id: '/charities',
  path: '/charities',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CharitiesIdRoute = CharitiesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CharitiesRoute,
} as any)
const AdminWinnersRoute = AdminWinnersRouteImport.update({
  id: '/admin/winners',
  path: '/admin/winners',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/charities': typeof CharitiesRouteWithChildren
  '/signup': typeof SignupRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/winners': typeof AdminWinnersRoute
  '/charities/$id': typeof CharitiesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/charities': typeof CharitiesRouteWithChildren
  '/signup': typeof SignupRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/winners': typeof AdminWinnersRoute
  '/charities/$id': typeof CharitiesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/charities': typeof CharitiesRouteWithChildren
  '/signup': typeof SignupRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/winners': typeof AdminWinnersRoute
  '/charities/$id': typeof CharitiesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/charities'
    | '/signup'
    | '/admin/reports'
    | '/admin/winners'
    | '/charities/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/charities'
    | '/signup'
    | '/admin/reports'
    | '/admin/winners'
    | '/charities/$id'
  id:
    | '__root__'
    | '/'
    | '/charities'
    | '/signup'
    | '/admin/reports'
    | '/admin/winners'
    | '/charities/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CharitiesRoute: typeof CharitiesRouteWithChildren
  SignupRoute: typeof SignupRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminWinnersRoute: typeof AdminWinnersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/charities': {
      id: '/charities'
      path: '/charities'
      fullPath: '/charities'
      preLoaderRoute: typeof CharitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/charities/$id': {
      id: '/charities/$id'
      path: '/$id'
      fullPath: '/charities/$id'
      preLoaderRoute: typeof CharitiesIdRouteImport
      parentRoute: typeof CharitiesRoute
    }
    '/admin/winners': {
      id: '/admin/winners'
      path: '/admin/winners'
      fullPath: '/admin/winners'
      preLoaderRoute: typeof AdminWinnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CharitiesRouteChildren {
  CharitiesIdRoute: typeof CharitiesIdRoute
}

const CharitiesRouteChildren: CharitiesRouteChildren = {
  CharitiesIdRoute: CharitiesIdRoute,
}

const CharitiesRouteWithChildren = CharitiesRoute._addFileChildren(
  CharitiesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CharitiesRoute: CharitiesRouteWithChildren,
  SignupRoute: SignupRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminWinnersRoute: AdminWinnersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
